"""Reference primitives for repository-derived coding-agent evaluations."""

from .agent_boundary import (
    AgentBoundaryError,
    AgentInvocation,
    AgentRequest,
    FileReplacement,
    PatchArtifact,
    PatchValidationError,
    SourceFile,
    apply_patch_artifact,
    capture_request,
    parse_patch_artifact,
    run_controlled_adapter,
    validate_patch_artifact,
)
from .controlled import (
    TASK_DEFINITIONS,
    ControlledRepository,
    ControlledTaskDefinition,
    build_controlled_repository,
    write_trusted_verifier,
)
from .controlled_agent import (
    ControlledAgentReceipt,
    ControlledAgentSuiteReceipt,
    controlled_mock_adapter_path,
    replay_controlled_agent_suite,
)
from .falsification import (
    FalsificationEvidence,
    FalsificationFixture,
    FalsificationResult,
    Finding,
    check_fixture,
    falsify,
    load_fixture,
)
from .replay import (
    ReplayError,
    ReplayReceipt,
    ReplaySuiteReceipt,
    ReplayTask,
    SnapshotSecurityError,
    VerificationRun,
    replay_suite,
    replay_task,
    snapshot_commit,
    tree_sha256,
)
from .schemas import (
    AgentConfiguration,
    DecisionReceipt,
    EnvironmentPolicy,
    TaskManifest,
    TaskQualityRecord,
    ValidationCode,
)

__all__ = [
    "TASK_DEFINITIONS",
    "AgentBoundaryError",
    "AgentConfiguration",
    "AgentInvocation",
    "AgentRequest",
    "ControlledAgentReceipt",
    "ControlledAgentSuiteReceipt",
    "ControlledRepository",
    "ControlledTaskDefinition",
    "DecisionReceipt",
    "EnvironmentPolicy",
    "FalsificationEvidence",
    "FalsificationFixture",
    "FalsificationResult",
    "FileReplacement",
    "Finding",
    "PatchArtifact",
    "PatchValidationError",
    "ReplayError",
    "ReplayReceipt",
    "ReplaySuiteReceipt",
    "ReplayTask",
    "SnapshotSecurityError",
    "SourceFile",
    "TaskManifest",
    "TaskQualityRecord",
    "ValidationCode",
    "VerificationRun",
    "apply_patch_artifact",
    "build_controlled_repository",
    "capture_request",
    "check_fixture",
    "controlled_mock_adapter_path",
    "falsify",
    "load_fixture",
    "parse_patch_artifact",
    "replay_controlled_agent_suite",
    "replay_suite",
    "replay_task",
    "run_controlled_adapter",
    "snapshot_commit",
    "tree_sha256",
    "validate_patch_artifact",
    "write_trusted_verifier",
]

__version__ = "0.3.0"
